apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Assuming you are using Nginx Ingress Controller
  rules:
  - host: a940eb1476ab44729a62d28d866fb9c1-935096736.us-east-1.elb.amazonaws.com  # Use the DNS name of your ELB
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-app-service
            port:
              number: 80